# Generated by Django 5.0.4 on 2024-04-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('education_level', models.CharField(choices=[('High School', 'Secundaria'), ('Preparatory', 'Preparatoria'), ('Bachelor', 'Licenciatura')], max_length=50)),
                ('currently_employed', models.BooleanField(default=False)),
                ('sales_experience', models.BooleanField(default=False)),
            ],
        ),
    ]
