# Generated by Django 5.0.4 on 2024-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='education_level',
            field=models.CharField(max_length=100),
        ),
    ]
