# Generated by Django 5.0.4 on 2024-04-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_alter_prospect_education_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='full_name',
        ),
        migrations.AddField(
            model_name='prospect',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='prospect',
            name='mother_last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
